version: '3.8'

services:
  python:
    build:
      context: ./python
    container_name: chess_engine_python
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./python/src:/app/src
      - ./python/tests:/app/tests
      - ./notebooks:/app/notebooks 
    networks:
      - chess-network
    environment:
    - JUPYTER_TOKEN=easy

  # go:
  #   build:
  #     context: ./go
  #   container_name: chess_engine_go
  #   ports:
  #     - "6000:6000"
  #   networks:
  #     - chess-network

networks:
  chess-network:
    driver: bridge