version: '3.8'

services:
  go:
    build:
      context: ./go
    container_name: chess_engine_go
    ports:
      - "6000:6000"
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge